apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app.kubernetes.io/name: iptables-viz-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
